version: '3.9'
services:
  tracer:
    image: 'jaegertracing/all-in-one'
    environment: 
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  db:
    image: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
       - db-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"

  db-ui:
    image: adminer
    ports: 
      - 8282:8080
volumes:
  db-data:
